### PR TITLE
ZEN-27622: Wrong device status in the UI

### PR DESCRIPTION
**Pull request by olst**

### CODE REVIEW

**Comment by rphillipsz** [comment]
I did a quick search, and the current status class is being used like this in about a dozen other zenpacks.. is it broken in the other zenpacks also?

**Comment by olst** [comment]
Just checked `/ControlCenter` device and yes, the same issue.

**Comment by jplouis** [comment]
@cluther Could you take a look at this? Is this something that needs to be fixed for other zenpacks?

**Comment by olst** [comment]
I've found these zenpacks:

```
zenoss/ZenPacks.zenoss.ControlCenter – ControlCenter.py
zenoss/ZenPacks.zenoss.CiscoVIM – zenpacklib.py
zenoss/ZenPacks.zenoss.vSphere – zenpacklib.py
zenoss/ZenPacks.zenoss.HP.Proliant – zenpacklib.py
zenoss/ZenPacks.zenoss.Docker – zenpacklib.py
zenoss/ZenPacks.zenoss.PS.Commvault – zenpacklib.py
zenoss/ZenPacks.zenoss.PS.EMCDataDomain – zenpacklib.py
zenoss/ZenPacks.zenoss.Tandberg – zenpacklib.py
zenoss/ZenPacks.zenoss.OpenvSwitch – zenpacklib.py
zenoss/ZenPacks.zenoss.Ceph – zenpacklib.py
zenoss/ZenPacks.zenoss.PS.EMCRecoverPoint – zenpacklib.py
zenoss/ZenPacks.zenoss.Microsoft.Azure – AzureSubscription.py
zenoss/ZenPacks.zenoss.AWS – EC2Account.py
zenoss/ZenPacks.zenoss.OpenStackInfrastructure – Endpoint.py
```

**Comment by cluther** [comment]
@olst, @jplouis: I can't say for the PS ZenPacks, but it appears that ControlCenter might be the only other ZenPack negatively affected by this issue. The rest of the listed ZenPacks aren't affected for one of two reasons. Either their status events are directly in the /Status event class because they aren't ping monitored, or because they don't even have a custom device type on which the status implementation becomes overridden.

This looks to mainly be a bug in ZenPackLib 1.x. It has been fixed in the zenpackified and centralized ZenPackLib 2.x as of its first (2.0.0) release.
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/commit/01673d20a7ac85f72a857944776dc44becd4fbcc

**Comment by jplouis** [comment]
Control Center zenpack is also set to zPingMonitorIgnore=True. So if there are no concerns for the other solutions zenpack then this seems fine. I assume moving this zenpack to zenpacklib 2.x is out of scope.

**Comment by dbouchillon** [comment]
In ZPL2(ZenPacks.zenoss.ZenPackLib), this issue has been fixed by this same code change.

Approved

**Comment by dbouchillon** [comment]
Yes, 2.3.0 will be moving to zpl2.

This should actually be in a hotfix branch instead of on develop though

**Comment by dbouchillon** [comment]
changes requested

**Pull request closed without merging**
