### PR TITLE
ZEN-27112 Flare error message appears when click on filesystem compon…

### PR DESCRIPTION
**Pull request by romanbakaleyko**
…ent of windows device.

### CODE REVIEW

**Comment by romanbakaleyko** [comment]
should go with https://github.com/zenoss/zenoss-prodbin/pull/2215

**Comment by romanbakaleyko** [comment]
port https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/pull/152

**Comment by jpeacock-zenoss** [comment]
Why is there a hotfix?

**Comment by romanbakaleyko** [comment]
Chet told me to do this as a hotfix, and push to product-assembly a hotfix but not a develop version.

**Pull request merged**
